### ISSUE TITLE
Update to work with more recent starlette versions

### ISSUE THREAD

**Issue by abingham** [jockerz/Starlette-Login#4]
I'm running into problems that seem to come from changes in starlette. I'm using starlette 0.37.2 and starlette-login 0.2.1.

What I see is that starlette's authentication middleware doesn't like the return result from `SessionAuthBackend.authenticate()`. Here's a partial stack trace:
```
File "/Users/austin/.virtualenvs/tubetrain-webapp-dev/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/austin/.virtualenvs/tubetrain-webapp-dev/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Users/austin/.virtualenvs/tubetrain-webapp-dev/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/austin/.virtualenvs/tubetrain-webapp-dev/lib/python3.12/site-packages/starlette/middleware/sessions.py", line 85, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/Users/austin/.virtualenvs/tubetrain-webapp-dev/lib/python3.12/site-packages/starlette/middleware/authentication.py", line 48, in __call__
    scope["auth"], scope["user"] = auth_result
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable User object
```

The return value from `SessionAuthBackend.authenticate()` is the `UserMixin` subclass I've created. But starlette wants to unpack it as a sequence with two elements. So my guess is that this unpacking is a new thing representing some change in the starlette API.

First, am I diagnosing this correctly, or am I making a mistake somewhere else?

Second, if I'm diagnosing this correctly, do you have any plans to upgrade to more recent starlette versions?

**Comment by abingham** [comment]
It looks like the relevant issue is that [`AuthenticationBackend.authenticate()` needs to return a tuple of `[AuthCredentials, BaseUser]`](https://www.starlette.io/authentication/).

**Comment by abingham** [comment]
On further investigation, it seems that I can just return that `[AuthCredentials, BaseUser]` tuple from my user-loader callable. When I do this, everything seems to work. 

Is this actually OK to do? Is there any other part of starlette-login that uses the user-loader?

If doing this is OK, then the documentation should be updated to reflect it.

**Comment by jockerz** [comment]
Hi @abingham.
Thank you for pointing this issue.
I will look into it as soon as possible and inform the update of it.

**Comment by jockerz** [comment]
Hi @abingham.
I still working on the issue.

Btw, 
Do you  use **starlette_login**  `AuthenticationMiddleware`?

the import is `from starlette_login.middleware import AuthenticationMiddleware`.

Here is the usage example:

```python
from starlette.middleware.sessions import SessionMiddleware
from starlette_login.backends import SessionAuthBackend

from starlette_login.middleware import AuthenticationMiddleware


app = Starlette(
    middleware=[
        Middleware(SessionMiddleware, secret_key='secret'),    # required
        Middleware(
            AuthenticationMiddleware,
            ...
        )
    ],
    ...
)
```

The complete example is on the [documentation](https://starlette-login.readthedocs.io/en/stable/)

**Comment by abingham** [comment]
Yes, we're using `AuthenticationMiddleware`.

**Comment by jockerz** [comment]
Hi @abingham, please try change `SessionAuthBackend` to `SessionMiddleware`.

Apologize late response.
Hope you find the solution

**Comment by abingham** [comment]
I'm not sure I understand what you're asking me to do. Do you want me to change:
```
app.add_middleware(
    AuthenticationMiddleware,
    backend=SessionAuthBackend(login_manager),
)
```
to:
```
app.add_middleware(
    AuthenticationMiddleware,
    backend=SessionMiddleware(login_manager),
)
```
? I don't see how this makes any sense, so I must be be misunderstanding something.

**Comment by jockerz** [comment]
> Hi @abingham, please try change `SessionAuthBackend` to `SessionMiddleware`.
> 
> Apologize late response. Hope you find the solution

Hi @abingham.
I am sorry, i explained this badly

To solve the issue, we should change the `Authentication` class

Previous (with error): `from starlette.middleware.authentication import AuthenticationMiddleware`
To: `from starlette_login.middleware import AuthenticationMiddleware`

**Comment by jockerz** [comment]
To reproduce the issue, 
lets try with example from [documentation](https://starlette-login.readthedocs.io/en/stable/)

And please take a look on comment on the script below.

Then the `app.py` edited like this

```python
from starlette.applications import Starlette
from starlette.middleware import Middleware
from starlette.middleware.sessions import SessionMiddleware
from starlette.routing import Route

# Here come the issue on login
from starlette.middleware.authentication import AuthenticationMiddleware
# We should use this instead
# from starlette_login.middleware import AuthenticationMiddleware

from starlette_login.backends import SessionAuthBackend
from starlette_login.login_manager import LoginManager

from model import user_list
from routes import home_page, login_page, logout_page, protected_page


login_manager = LoginManager(redirect_to='login', secret_key='secret')
login_manager.set_user_loader(user_list.user_loader)

app = Starlette(
    middleware=[
        Middleware(SessionMiddleware, secret_key='secret'),
        Middleware(
            AuthenticationMiddleware,
            backend=SessionAuthBackend(login_manager),
        )
    ],

    routes=[
        Route('/', home_page, name='home'),
        Route('/login', login_page, methods=['GET', 'POST'], name='login'),
        Route('/logout', logout_page, name='logout'),
        Route('/protected', protected_page, name='protected'),
    ],
)
app.state.login_manager = login_manager
```

Run the web app: `uvicorn app:app`

Try the `/login` endpoint to reproduce the issue.

**Comment by jockerz** [comment]
I am very sorry for late response.
Need to get some stuff done these few days.

**Comment by abingham** [comment]
> I am very sorry for late response.

No problem at all. I completely understand how hard it can be to find time to maintain open-source projects.

I think I finally understand all of the pieces to this problem. I switched to using `starlette_login.middleware.AuthenticationMiddleware`, and I was able to make things work.

However, I think that I really _do_ want to use `starlette.middleware.authentication.AuthenticationMiddleware` because of its `AuthPermissions`/credentials system. This has turned out to be very useful for us, and starlette-login doesn't seem to offer an alternative.

So I'm back to using your `SessionAuthBackend` with starlette's standard `AuthenticationMiddleware`. My user loader is returning a `(AuthCredentials, User)` tuple which is fortunately returned unchanged by the `SessionAuthBackend`. This system works for me and gives me everything I need. 

My main concern is that your `SessionAuthBackend` isn't really designed to work with starlette's standard authentication middleware, so it seems this all only works by luck, not by design. You could potentially make reasonable changes to startlette-login that break my system, and I don't like that fragility. 

So from my perspective I see a few options:

- Keep working with the combination of `starlette.middleware.authentication.AuthenticationMiddleware` and `startlette_login.backends.SessionAuthBackend`. I'll do this for the near term.
- Port/clone your `SessionAuthBackend` so that I can guarantee that it works with the middleware
- Update `starlette_login` to have a concept of 'credentials' similar to starlette's native authentication middleware. This would include adding a `requires` decorator. 
- Update your `SessionAuthBackend` to explicitly work with starlette's authentication middlware. This would probably require changes to your middleware as well. Or perhaps starlette-login doesn't need to provide middleware. From my position, the real value of starlette-login is in the backend; it's not clear to me if its middlware provides anything beyond the standard authentication middlware.

Thanks for helping me work through this. You've written a really useful bit of software, and I just need to find the best way to use it in my project.

**Comment by jockerz** [comment]
Great advice, i should consider your advice as this module meant to extends Starlette.
I will working on it
By the way the update will be major version update. 

Thank you so much @abingham
